# Site settings
title: CachetHQ
email: jbrooksuk@me.com
description: > # this means to ignore newlines until "baseurl:"
  Cachet is an Open Source StatusPage.io alternative written in PHP.
baseurl: ""
url: "http://cachethq.io" # the base hostname & protocol for your site
timezone: Europe/London
project_title: Cachet

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed

# Social links (footer)
social:
  - title: twitter
    url: https://twitter.com/cachethq
  - title: github
    url: https://github.com/cachethq
  - title: envelope
    url: mailto:support@cachethq.io

# About text
about: Open Source StatusPage.io alternative written in PHP.

exclude:
  - "bower.json"
  - "bower_components"
  - "package.json"
  - "npm_modules"
  - "elixir.json"
  - "gulpfile.js"
  - "readme.md"
